#!/usr/bin/env python3
"""
FinFriend Setup Tool

Pre-authorization tool that registers with aitools-llm-proxy and generates 
a complete .env file for FinFriend to use the free opensource LLM endpoint.

Usage:
    python finfriend-setup.py --username USERNAME --pin PIN
    python finfriend-setup.py --username USERNAME --pin PIN --verify
"""

import argparse
import os
import sys
from typing import Optional
import httpx
from datetime import datetime

def print_status(message: str, success: bool = True) -> None:
    """Print status message with color coding."""
    prefix = "✓" if success else "✗"
    print(f"{prefix} {message}")

def register_user(username: str, pin: str, proxy_url: str = "http://aitools.cs.vt.edu:7860") -> Optional[str]:
    """
    Register user with aitools-llm-proxy and return JWT token.
    
    Args:
        username: Username for registration
        pin: 4-digit PIN for registration  
        proxy_url: Base URL for the proxy service
        
    Returns:
        JWT token if successful, None if failed
    """
    try:
        with httpx.Client(timeout=30) as client:
            response = client.post(
                f"{proxy_url}/auth/register",
                json={"username": username, "pin": pin}
            )
            
            if response.status_code == 200:
                data = response.json()
                token = data.get('token')
                if token:
                    print_status(f"Successfully registered user: {username}")
                    return token
                else:
                    print_status("Registration failed: No token received", False)
                    return None
            else:
                error_msg = f"Registration failed: {response.status_code}"
                if response.status_code == 403:
                    error_msg += " (Invalid username or PIN)"
                elif response.status_code == 400:
                    error_msg += " (PIN must be exactly 4 digits)"
                print_status(error_msg, False)
                return None
                
    except Exception as e:
        print_status(f"Registration error: {e}", False)
        return None

def verify_token(token: str, proxy_url: str = "http://aitools.cs.vt.edu:7860") -> bool:
    """
    Verify the JWT token works by making a test API call.
    
    Args:
        token: JWT token to test
        proxy_url: Base URL for the proxy service
        
    Returns:
        True if token works, False otherwise
    """
    try:
        with httpx.Client(timeout=30) as client:
            headers = {
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json"
            }
            
            payload = {
                "model": "openai--gpt-oss-120b",
                "messages": [{"role": "user", "content": "Hello"}],
                "max_tokens": 5,
                "stream": False
            }
            
            response = client.post(
                f"{proxy_url}/opensource/v1/chat/completions",
                headers=headers,
                json=payload
            )
            
            if response.status_code == 200:
                print_status("Token verification successful")
                return True
            else:
                print_status(f"Token verification failed: {response.status_code}", False)
                return False
                
    except Exception as e:
        print_status(f"Token verification error: {e}", False)
        return False

def backup_existing_env() -> bool:
    """
    Create backup of existing .env file if it exists.
    
    Returns:
        True if backup created or no file exists, False on error
    """
    if not os.path.exists('.env'):
        return True
        
    try:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        backup_name = f'.env.backup.{timestamp}'
        
        with open('.env', 'r') as src, open(backup_name, 'w') as dst:
            dst.write(src.read())
            
        print_status(f"Existing .env backed up to {backup_name}")
        return True
        
    except Exception as e:
        print_status(f"Failed to backup existing .env: {e}", False)
        return False

def write_env_file(token: str) -> bool:
    """
    Write .env file with FinFriend configuration.
    
    Args:
        token: JWT token to use as API key
        
    Returns:
        True if successful, False otherwise
    """
    try:
        env_content = f"""# FinFriend Configuration - Generated by finfriend-setup
# Generated: {datetime.now().isoformat()}

# LLM Configuration for free aitools-llm-proxy access
OPENAI_API_BASE_URL=http://aitools.cs.vt.edu:7860/opensource/v1
OPENAI_API_KEY={token}
OPENAI_API_MODEL=openai--gpt-oss-120b
"""
        
        with open('.env', 'w') as f:
            f.write(env_content)
            
        print_status("Generated .env file with aitools-llm-proxy configuration")
        return True
        
    except Exception as e:
        print_status(f"Failed to write .env file: {e}", False)
        return False

def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="FinFriend Setup Tool - Register with aitools-llm-proxy and generate .env file",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python finfriend-setup.py --username alice --pin 1234
    python finfriend-setup.py --username alice --pin 1234 --verify
        """
    )
    
    parser.add_argument('--username', required=True,
                       help='Username for aitools-llm-proxy registration (required)')
    parser.add_argument('--pin', required=True,
                       help='4-digit PIN for registration (required)')
    parser.add_argument('--verify', action='store_true',
                       help='Verify token works before writing .env file')
    parser.add_argument('--proxy-url', default='http://aitools.cs.vt.edu:7860',
                       help='Proxy base URL (default: http://aitools.cs.vt.edu:7860)')
    
    args = parser.parse_args()
    
    print("=" * 60)
    print("FinFriend Setup - aitools-llm-proxy Registration".center(60))
    print("=" * 60)
    print(f"Username: {args.username}")
    print(f"Proxy URL: {args.proxy_url}")
    print()
    
    # Register user and get token
    print("Registering with aitools-llm-proxy...")
    token = register_user(args.username, args.pin, args.proxy_url)
    if not token:
        print("\nSetup failed. Please check your username and PIN.")
        return 1
    
    # Verify token if requested
    if args.verify:
        print("\nVerifying token...")
        if not verify_token(token, args.proxy_url):
            print("\nSetup failed. Token verification failed.")
            return 1
    
    # Backup existing .env file
    print("\nPreparing configuration...")
    if not backup_existing_env():
        print("\nWarning: Could not backup existing .env file. Continuing anyway...")
    
    # Write new .env file
    if not write_env_file(token):
        print("\nSetup failed. Could not write .env file.")
        return 1
    
    # Success message
    print("\n" + "=" * 60)
    print("Setup Complete!".center(60))
    print("=" * 60)
    print("✓ User registered with aitools-llm-proxy")
    print("✓ .env file generated with free opensource LLM configuration")
    print("✓ Ready to use FinFriend with openai--gpt-oss-120b model")
    print()
    print("Next steps:")
    print("1. Run: uv run streamlit run 🏠_FinFriend.py")
    print("2. Enjoy free AI-powered personal finance assistance!")
    print()
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
